name: Deploy to Server
on:
  push:
    branches: [ main ]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with: 
          host: maxk.eu
          username: m4x
          key: ${{ secrets.KICKBASEDEPLOY }}
          port: 22
          script: | 
            cd ~/kickbase
            git pull origin main
            git status
          










